import './globals.css'
import { Montserrat } from 'next/font/google'

const monserrat = Montserrat({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: "--font-monserrat",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monserrat.className} mx-32 my-12`}>
        <nav>
          <ul>
            <li>
              <a className='fontFamily-montserrat' href="/">Home</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
